### ISSUE TITLE
I've tried simpleParallax and simply love it but its not working on Safari

### ISSUE THREAD

**Issue by drstrangelovesg** [geosigno/simpleParallax#23] opened 2019-08-09 15:56 UTC
Is there any way we can make this work on Safari? I checked the samples site and it is not working on Safari either.

Thanks for the great work!

**Comment by geosigno** [comment] 2019-08-15 09:53
Hi drstrangelovesg,
This is working fine for me on Safari... which version are you using?

**Comment by drstrangelovesg** [comment] 2019-08-17 06:01
> Hi drstrangelovesg,
> This is working fine for me on Safari... which version are you using?

Hi Geosigno,

Apology for my late reply, madness few days. I'm using Safari version 12.0.2 (14606.3.4).

Cheers

**Comment by drstrangelovesg** [comment] 2019-08-17 06:07
Hi @geosigno 

I further check, on Safari 12.1.1.

And it is working fine on that version. but on the 12.0. version though.

Hope this help.

Cheers

**Comment by geosigno** [comment] 2019-08-18 14:28
This is a bit weird, but if this is working fine on the latest version I don't think any fix is needed. Most probably this Safari version had an issue. I close this issue for the moment, feel free to re-open it if the issue is reproducible.

**Closed by geosigno** 2019-08-18 14:28 UTC

**Comment by graphis** [comment] 2021-05-24 15:50
safari v 12.0.2  /  13606.3.4.1.4 has also this issue :(
